# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_to_ast.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'text_to_ast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11text_to_ast.proto\x12\x06jarvis\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\">\n\x15TextToAstConversation\x12%\n\x08messages\x18\x01 \x03(\x0b\x32\x13.jarvis.ChatMessage2X\n\tTextToAst\x12K\n\x0bProcessText\x12\x1d.jarvis.TextToAstConversation\x1a\x1d.jarvis.TextToAstConversationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_to_ast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=29
  _globals['_CHATMESSAGE']._serialized_end=73
  _globals['_TEXTTOASTCONVERSATION']._serialized_start=75
  _globals['_TEXTTOASTCONVERSATION']._serialized_end=137
  _globals['_TEXTTOAST']._serialized_start=139
  _globals['_TEXTTOAST']._serialized_end=227
# @@protoc_insertion_point(module_scope)
